name: Deploy Laravel API to api.smartlis.site

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Extract Commit Message
        id: get_message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Parse Version dari Commit
        run: |
          VERSION=$(echo "$MESSAGE" | grep -oP "\|update-version:\K[0-9]+\.[0-9]+\.[0-9]+" || echo "")
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Detect fresh/seed (branch dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "ISFRESH=$(echo $MESSAGE | grep -q '|fresh' && echo true || echo false)" >> $GITHUB_ENV
          echo "ISSEED=$(echo $MESSAGE | grep -q '|seed' && echo true || echo false)" >> $GITHUB_ENV

      - name: Deploy ke VPS
        run: |
          # Tentukan path & domain
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            PATH_SERVER="/var/www/api.smartlis.site"
            MIGRATE="php artisan migrate --force"
          else
            PATH_SERVER="/var/www/dev.api.smartlis.site"
            MIGRATE="php artisan migrate --force"
            $([[ "$ISFRESH" == "true" ]] && MIGRATE="php artisan migrate:fresh --force")
            $([[ "$ISSEED"  == "true" ]] && MIGRATE="$MIGRATE && php artisan db:seed --force")
          fi

          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} << EOF
            cd $PATH_SERVER
            git pull origin ${GITHUB_REF##*/}
            composer install --no-dev --optimize-autoloader
            $MIGRATE
            if [[ -n "$APP_VERSION" ]]; then
              sed -i "s/^APP_VERSION=.*/APP_VERSION=$APP_VERSION/" .env
            fi
            php artisan config:clear && php artisan cache:clear \
              && php artisan route:clear && php artisan view:clear
            systemctl restart nginx
          EOF
